language: node_js
node_js: node

cache:
  directories:
    - "node_modules"
    - "server/node_modules"
    - "client/node_modules"

before_script:
  - npm install  
  - npm run postinstall
  - npm run build

# script:
#   - npm run test-only

# after_success:
#   - npm run typedoc
before_deploy: 
  - npm install 
  - npm build

deploy:
  provider: azure_web_apps
  verbose: true